# MaxLocksPerFile - Limits MS access in the number of rows it may be able to process.  Typically not a problem.  However, saving table designs on large tables may be an issue.  Locations I have found the locks set.

MaxLocksPerFile = [
    'SOFTWARE\Microsoft\Jet\4.0\Engines\Jet 4.0',
    'SOFTWARE\Microsoft\Office\12.0\Access Connectivity Engine\Engines\ACE',
    'SOFTWARE\Microsoft\Office\14.0\Access Connectivity Engine\Engines\ACE',
    'SOFTWARE\Microsoft\Office\14.0\Access Connectivity Engine\Engines\Jet 3.x',
    'SOFTWARE\Microsoft\Office\15.0\Access Connectivity Engine\Engines\ACE',
    'SOFTWARE\Microsoft\Office\16.0\Access Connectivity Engine\Engines\ACE',
    'SOFTWARE\Microsoft\Office\ClickToRun\REGISTRY\MACHINE\Software\Wow6432Node\Microsoft\Office\16.0\Access Connectivity Engine\Engines\ACE',
    'SOFTWARE\WOW6432Node\Microsoft\Jet\4.0\Engines\Jet 3.x',
    'SOFTWARE\WOW6432Node\Microsoft\Jet\4.0\Engines\Jet 4.0',
    'SOFTWARE\Wow6432Node\Microsoft\Office\12.0\Access Connectivity Engine\Engines\ACE',
    'SOFTWARE\Wow6432Node\Microsoft\Office\14.0\Access Connectivity Engine\Engines\ACE',
    'SOFTWARE\Wow6432Node\Microsoft\Office\15.0\Access Connectivity Engine\Engines\ACE',
    'SOFTWARE\Wow6432Node\Microsoft\Office\16.0\Access Connectivity Engine\Engines\ACE',
]
